// Setup player as pass-through
params ["_target", "_caller", "_actionId", "_arguments"];
private _player = _this select 1;
private _class = _this select 3;
private _loadout = [];

// Which class are we using based on input.
switch (_class) do
{
	case "cmt": {
		_loadout = [["UK3CB_BAF_L85A3","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS_PiP",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_d"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["lb_16med_basic",[["KNB_Notebook",1],["BW_Facepaint",1],["ACE_CableTie",3],["ACE_EarPlugs",2],["greenmag_item_speedloader",1],["kat_chestSeal",2],["ACE_elasticBandage",5],["ACE_packingBandage",5],["ACE_quikclot",5],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["ACE_tourniquet",2],["kat_Painkiller",1,10]]],["mpx_virtus_Medic_p",[["baf_bayonet_compat",1],["ACRE_PRC343_ID_1",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["UK3CB_BAF_556_30Rnd",6,30],["HandGrenade",3,1],["UK3CB_BAF_SmokeShell",3,1]]],["mpx_daysack7",[["QAC_BUSHHAT_MTP_CORD_2",1],["greenmag_ammo_556x45_basic_30Rnd",4],["ACE_Canteen",2],["ACE_EntrenchingTool",1],["ACE_MRE_BeefStew",2],["kat_guedel",15],["ACE_tourniquet",10],["ACE_splint",8],["ACE_morphine",10],["ACE_epinephrine",15],["ACE_packingBandage",20],["ACE_elasticBandage",20],["ACE_quikclot",20],["3para_beret3_16medd",1],["kat_stethoscope",1],["kat_TXA",5],["kat_Pulseoximeter",2],["kat_nitroglycerin",5],["kat_naloxone",10],["kat_larynx",10],["kat_fentanyl",5],["kat_IO_FAST",5],["kat_chestSeal",5],["kat_crossPanel",1],["kat_IV_16",20],["ACE_surgicalKit",1],["ACE_salineIV",1],["ACE_plasmaIV",1],["ACE_plasmaIV_500",2],["ACE_salineIV_500",2],["ACE_salineIV_250",4],["ACE_plasmaIV_250",4],["ACE_adenosine",5],["kat_accuvac",1],["kat_AED",1],["USP_PVS14",1],["kat_amiodarone",5],["Chemlight_green",3,1],["UK3CB_BAF_SmokeShellBlue",3,1],["UK3CB_BAF_SmokeShellPurple",3,1],["kat_Painkiller",3,10],["kat_Carbonate",1,10]]],"mpx_cobra_scrim","UK3CB_BAF_G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]]
	};

	case "teammedic":{
		_loadout = [["UK3CB_BAF_L85A3","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_d"],[],[],["lb_3para_basic",[["KNB_Notebook",1],["BW_Facepaint",1],["ACE_CableTie",3],["ACE_EarPlugs",2],["greenmag_item_speedloader",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_IR_Strobe_Item",2],["kat_Painkiller",1,10]]],["mpx_virtus2_p",[["baf_bayonet_compat",1],["ACRE_PRC343",1],["UK3CB_BAF_556_30Rnd",6,30],["HandGrenade",3,1],["UK3CB_BAF_SmokeShell",3,1]]],["mpx_daysack8",[["greenmag_ammo_556x45_basic_30Rnd",3],["ACE_Canteen",2],["ACE_EntrenchingTool",1],["ACE_MRE_BeefStew",2],["kat_guedel",10],["kat_chestSeal",10],["ACE_tourniquet",10],["ACE_splint",5],["ACE_packingBandage",25],["ACE_elasticBandage",25],["ACE_quikclot",25],["USP_PVS14",1],["ACE_plasmaIV_250",4],["ACE_plasmaIV_500",2],["ACE_salineIV_250",4],["ACE_salineIV_500",2],["kat_Pulseoximeter",5],["kat_naloxone",3],["kat_larynx",5],["kat_IV_16",5],["kat_accuvac",1],["ACE_plasmaIV",1],["ACE_salineIV",1],["Chemlight_green",3,1],["UK3CB_BAF_SmokeShellBlue",3,1],["UK3CB_BAF_SmokeShellPurple",3,1],["kat_Painkiller",1,10]]],"mpx_cobra_scrim","UK3CB_BAF_G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]
		]
	};

	case "rifleman": {
		_loadout = [["UK3CB_BAF_L85A3","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS_PiP",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_d"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["lb_3para_basic",[["KNB_Notebook",1],["BW_Facepaint",1],["ACE_CableTie",3],["ACE_EarPlugs",2],["greenmag_item_speedloader",1],["kat_chestSeal",2],["ACE_elasticBandage",5],["ACE_packingBandage",5],["ACE_quikclot",5],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_Clacker",1],["ACE_IR_Strobe_Item",2],["ACE_tourniquet",2],["kat_Painkiller",1,10]]],["mpx_virtus_p",[["baf_bayonet_compat",1],["ACRE_PRC343_ID_2",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["UK3CB_BAF_556_30Rnd",6,30],["HandGrenade",3,1],["UK3CB_BAF_SmokeShell",3,1]]],["mpx_daysack8",[["3para_beret3_parad",1],["QAC_BUSHHAT_MTP_CORD_2",1],["greenmag_ammo_556x45_basic_30Rnd",6],["ACE_Canteen",2],["ACE_EntrenchingTool",1],["ACE_MRE_BeefStew",2],["kat_guedel",3],["kat_chestSeal",1],["ACE_tourniquet",3],["ACE_splint",3],["ACE_morphine",3],["ACE_epinephrine",3],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_fieldDressing",5],["ACE_quikclot",5],["USP_PVS14",1],["ClaymoreDirectionalMine_Remote_Mag",1,1],["UK3CB_BAF_762_100Rnd_T",1,100],["Chemlight_green",3,1],["UK3CB_BAF_SmokeShellBlue",3,1],["UK3CB_BAF_SmokeShellPurple",3,1]]],"mpx_cobra_scrim","UK3CB_BAF_G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]]
	};

	case "grenadier": {
		_loadout = [["UK3CB_BAF_L85A3_UGL","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS_PiP",["UK3CB_BAF_556_30Rnd",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["lb_3para_basic",[["KNB_Notebook",1],["BW_Facepaint",1],["ACE_CableTie",3],["ACE_EarPlugs",2],["greenmag_item_speedloader",1],["kat_chestSeal",2],["ACE_elasticBandage",5],["ACE_packingBandage",5],["ACE_quikclot",5],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_Clacker",1],["ACE_IR_Strobe_Item",2],["ACE_tourniquet",2],["kat_Painkiller",1,10]]],["mpx_virtus_p",[["baf_bayonet_compat",1],["ACRE_PRC343_ID_2",1],["HandGrenade",3,1],["UK3CB_BAF_SmokeShell",3,1],["UK3CB_BAF_556_30Rnd",6,30],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["mpx_daysack8",[["3para_beret3_parad",1],["QAC_BUSHHAT_MTP_CORD_2",1],["greenmag_ammo_556x45_basic_30Rnd",6],["ACE_Canteen",2],["ACE_EntrenchingTool",1],["ACE_MRE_BeefStew",2],["kat_guedel",3],["kat_chestSeal",1],["ACE_tourniquet",3],["ACE_splint",3],["ACE_morphine",3],["ACE_epinephrine",3],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_fieldDressing",5],["ACE_quikclot",5],["USP_PVS14",1],["UK3CB_BAF_Kite",1],["ClaymoreDirectionalMine_Remote_Mag",1,1],["UK3CB_BAF_762_100Rnd_T",1,100],["Chemlight_green",3,1],["UK3CB_BAF_SmokeShellBlue",3,1],["UK3CB_BAF_SmokeShellPurple",3,1],["UK3CB_BAF_1Rnd_HE_Grenade_Shell",19,1],["UK3CB_BAF_1Rnd_Smoke_Grenade_shell",5,1]]],"mpx_cobra_scrim","UK3CB_BAF_G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]]
	};

	case "sharpshooter": {
		_loadout = [["UK3CB_BAF_L129A1","","UK3CB_BAF_LLM_IR_Tan","UK3CB_BAF_TA648_308",["UK3CB_BAF_762_L42A1_20Rnd",20],[],"UK3CB_underbarrel_acc_fgrip_bipod"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["lb_3para_basic",[["KNB_Notebook",1],["BW_Facepaint",1],["ACE_CableTie",3],["ACE_EarPlugs",2],["greenmag_item_speedloader",1],["kat_chestSeal",2],["ACE_elasticBandage",5],["ACE_packingBandage",5],["ACE_quikclot",5],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_Clacker",1],["ACE_IR_Strobe_Item",2],["ACE_tourniquet",2],["ACE_Kestrel4500",1],["kat_Painkiller",1,10]]],["mpx_virtus_taco_p",[["ACRE_PRC343_ID_1",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["HandGrenade",2,1],["UK3CB_BAF_SmokeShell",3,1],["UK3CB_BAF_762_L42A1_20Rnd",4,20]]],["mpx_daysack8",[["3para_beret3_parad",1],["QAC_BUSHHAT_MTP_CORD_2",1],["ACE_Canteen",2],["ACE_EntrenchingTool",1],["ACE_MRE_BeefStew",2],["kat_guedel",3],["kat_chestSeal",1],["ACE_tourniquet",3],["ACE_splint",3],["ACE_morphine",3],["ACE_epinephrine",3],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_fieldDressing",5],["ACE_quikclot",5],["greenmag_ammo_762x51_basic_30Rnd",6],["USP_PVS14",1],["ClaymoreDirectionalMine_Remote_Mag",1,1],["Chemlight_green",3,1],["UK3CB_BAF_SmokeShellBlue",3,1],["UK3CB_BAF_SmokeShellPurple",3,1],["UK3CB_BAF_762_L42A1_20Rnd",1,20]]],"mpx_cobra_scrim","UK3CB_BAF_G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]]
	};

	case "gpmg": {
		_loadout = [["UK3CB_BAF_L7A2","","","",["UK3CB_BAF_762_100Rnd",100],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["lb_3para_basic",[["KNB_Notebook",1],["BW_Facepaint",1],["ACE_CableTie",3],["ACE_EarPlugs",2],["greenmag_item_speedloader",1],["kat_chestSeal",2],["ACE_elasticBandage",5],["ACE_packingBandage",5],["ACE_quikclot",5],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_Clacker",1],["ACE_IR_Strobe_Item",2],["ACE_tourniquet",2],["kat_Painkiller",1,10]]],["mpx_virtus3_p",[["ACRE_PRC343_ID_2",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["HandGrenade",3,1],["UK3CB_BAF_SmokeShell",3,1],["UK3CB_BAF_762_100Rnd_T",2,100]]],["mpx_daysack8",[["3para_beret3_parad",1],["QAC_BUSHHAT_MTP_CORD_2",1],["ACE_Canteen",2],["ACE_EntrenchingTool",1],["ACE_MRE_BeefStew",2],["kat_guedel",3],["kat_chestSeal",1],["ACE_tourniquet",3],["ACE_splint",3],["ACE_morphine",3],["ACE_epinephrine",3],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_fieldDressing",5],["ACE_quikclot",5],["greenmag_beltlinked_762x51_basic_100",6],["USP_PVS14",1],["ClaymoreDirectionalMine_Remote_Mag",1,1],["Chemlight_green",3,1],["UK3CB_BAF_SmokeShellBlue",3,1],["UK3CB_BAF_SmokeShellPurple",3,1],["UK3CB_BAF_762_100Rnd_T",2,100]]],"mpx_cobra_scrim","UK3CB_BAF_G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]]
	};

	case "pointman": {
		_loadout = [["UK3CB_BAF_L85A3_Grippod_D","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS_PiP",[],[],"UK3CB_underbarrel_acc_grippod_d"],[],["ACE_VMM3","","","",[],[],""],["lb_3para_basic",[["KNB_Notebook",1],["BW_Facepaint",1],["ACE_CableTie",3],["ACE_EarPlugs",2],["greenmag_item_speedloader",1],["kat_chestSeal",2],["ACE_elasticBandage",5],["ACE_packingBandage",5],["ACE_quikclot",5],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_Clacker",1],["ACE_IR_Strobe_Item",2],["ACE_tourniquet",2],["kat_Painkiller",1,10]]],["mpx_virtus_p",[["baf_bayonet_compat",1],["ACRE_PRC343_ID_1",1],["UK3CB_BAF_556_30Rnd",6,30],["HandGrenade",3,1],["UK3CB_BAF_SmokeShell",3,1]]],["mpx_daysack8",[["3para_beret3_parad",1],["QAC_BUSHHAT_MTP_CORD_2",1],["greenmag_ammo_556x45_basic_30Rnd",6],["ACE_Canteen",2],["ACE_EntrenchingTool",1],["ACE_MRE_BeefStew",2],["kat_guedel",3],["kat_chestSeal",1],["ACE_tourniquet",3],["ACE_splint",3],["ACE_morphine",3],["ACE_epinephrine",3],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_fieldDressing",5],["ACE_quikclot",5],["USP_PVS14",1],["UK3CB_BAF_Kite",1],["ItemAndroid",1],["ACE_DefusalKit",1],["ACE_SpraypaintRed",1],["ClaymoreDirectionalMine_Remote_Mag",1,1],["UK3CB_BAF_762_100Rnd_T",1,100],["Chemlight_green",3,1],["UK3CB_BAF_SmokeShellBlue",3,1],["UK3CB_BAF_SmokeShellPurple",3,1]]],"mpx_cobra_scrim","UK3CB_BAF_G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]]
	};

	case "ic": {
		_loadout = [["UK3CB_BAF_L85A3_UGL","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS_PiP",["UK3CB_BAF_556_30Rnd",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["lb_3para_basic",[["KNB_Notebook",1],["BW_Facepaint",1],["ACE_CableTie",3],["ACE_EarPlugs",2],["greenmag_item_speedloader",1],["kat_chestSeal",2],["ACE_elasticBandage",5],["ACE_packingBandage",5],["ACE_quikclot",5],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_Clacker",1],["ACE_IR_Strobe_Item",2],["ACE_tourniquet",2],["ItemAndroid",1],["kat_Painkiller",1,10]]],["mpx_virtus_admin_p",[["baf_bayonet_compat",1],["ACRE_PRC343_ID_2",1],["ACRE_PRC152_ID_1",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["HandGrenade",3,1],["UK3CB_BAF_SmokeShell",3,1],["UK3CB_BAF_556_30Rnd",6,30]]],["mpx_daysack9",[["3para_beret3_parad",1],["QAC_BUSHHAT_MTP_CORD_2",1],["greenmag_ammo_556x45_basic_30Rnd",6],["ACE_Canteen",2],["ACE_EntrenchingTool",1],["ACE_MRE_BeefStew",2],["kat_guedel",3],["kat_chestSeal",1],["ACE_tourniquet",3],["ACE_splint",3],["ACE_morphine",3],["ACE_epinephrine",3],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_fieldDressing",5],["ACE_quikclot",5],["USP_PVS14",1],["ClaymoreDirectionalMine_Remote_Mag",1,1],["Chemlight_green",3,1],["UK3CB_BAF_SmokeShellBlue",3,1],["UK3CB_BAF_SmokeShellPurple",3,1],["1Rnd_Smoke_Grenade_shell",5,1],["1Rnd_HE_Grenade_shell",10,1],["UGL_FlareRed_F",3,1],["1Rnd_SmokeRed_Grenade_shell",5,1]]],"mpx_cobra_scrim","UK3CB_BAF_G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]]
	};

	case "pf-selection": {
		_loadout = [[],[],[],["UK3CB_BAF_U_Smock_MTP",[["ACE_MapTools",1],["BW_Facepaint",1],["ACE_Canteen",1],["ACE_Flashlight_MX991",1],["ACE_MRE_BeefStew",1]]],[],[],"","",[],["ItemMap","","","ItemCompass","ItemWatch",""]]
	};

	case "pf-rifleman": {
		_loadout = [["UKSF_L119A1CQB","","UKSF_RailCovers_3","UKSF_AR_ACOG",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["USP_G3C_CU_MC",[["ACE_microDAGR",1],["ACE_EarPlugs",3],["ACE_tourniquet",2],["ItemcTabHCam",1],["greenmag_item_speedloader",1],["ACE_CableTie",2],["BW_Facepaint",1],["ItemAndroid",1],["ACRE_PRC343",1],["ACE_Clacker",1]]],["USP_CRYE_CPC_LIGHT_BELT_MC",[["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["HandGrenade",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",2,30],["rhs_mag_30Rnd_556x45_M855A1_PMAG",5,30],[["UK3CB_BAF_Soflam_Laserdesignator","","","",[],[],""],1]]],["UK3CB_BAF_B_Kitbag_MTP",[["ACE_Canteen",2],["ACE_MRE_SteakVegetables",2],["ACE_SpraypaintBlue",1],["ACE_SpraypaintGreen",1],["ACE_SpraypaintRed",1],["ACE_MapTools",1],["ACE_EntrenchingTool",1],["greenmag_ammo_556x45_basic_30Rnd",4],["ACE_fieldDressing",8],["ACE_elasticBandage",8],["ACE_packingBandage",6],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["3para_beret3_para",1],["BW_Facepaint",1],["ACE_SpraypaintBlack",1],["USP_PVS31_LOW",1],["TFV_headgear_opscore_cover_mc_peltor",1],["ACRE_PRC152",1],["UK3CB_BAF_SmokeShellGreen",2,1],["UK3CB_BAF_SmokeShellOrange",2,1],["UK3CB_BAF_SmokeShellRed",2,1],["UK3CB_BAF_SmokeShellBlue",2,1],["UK3CB_BAF_SmokeShell",4,1]]],"QAC_BUSHHAT_MTP_CORDLESS","",["ACE_Vector","","","",[],[],""],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ACE_Altimeter",""]]
	};

	default {
		_loadout = [["UK3CB_BAF_L85A3","","UK3CB_BAF_LLM_IR_Tan","RKSL_optic_LDS_PiP",["UK3CB_BAF_556_30Rnd",30],[],"UK3CB_underbarrel_acc_grippod_d"],[],["rhsusf_weap_glock17g4","","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["lb_3para_basic",[["KNB_Notebook",1],["BW_Facepaint",1],["ACE_CableTie",3],["ACE_EarPlugs",2],["greenmag_item_speedloader",1],["kat_chestSeal",2],["ACE_elasticBandage",5],["ACE_packingBandage",5],["ACE_quikclot",5],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_Clacker",1],["ACE_IR_Strobe_Item",2],["ACE_tourniquet",2],["kat_Painkiller",1,10]]],["mpx_virtus_p",[["baf_bayonet_compat",1],["ACRE_PRC343_ID_2",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["UK3CB_BAF_556_30Rnd",6,30],["HandGrenade",3,1],["UK3CB_BAF_SmokeShell",3,1]]],["mpx_daysack8",[["3para_beret3_parad",1],["QAC_BUSHHAT_MTP_CORD_2",1],["greenmag_ammo_556x45_basic_30Rnd",6],["ACE_Canteen",2],["ACE_EntrenchingTool",1],["ACE_MRE_BeefStew",2],["kat_guedel",3],["kat_chestSeal",1],["ACE_tourniquet",3],["ACE_splint",3],["ACE_morphine",3],["ACE_epinephrine",3],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_fieldDressing",5],["ACE_quikclot",5],["USP_PVS14",1],["ClaymoreDirectionalMine_Remote_Mag",1,1],["UK3CB_BAF_762_100Rnd_T",1,100],["Chemlight_green",3,1],["UK3CB_BAF_SmokeShellBlue",3,1],["UK3CB_BAF_SmokeShellPurple",3,1]]],"mpx_cobra_scrim","UK3CB_BAF_G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch",""]]
	};
};

// Set player loadout.
_player setUnitLoadout _loadout;
