_spawner = _this select 0;
_spawner addaction ["Spawn Crate Alpha",	"scripts\spawners\logistics\crates.sqf", "alpha"];
_spawner addaction ["Spawn Crate Bravo", 	"scripts\spawners\logistics\crates.sqf", "bravo"];
_spawner addaction ["Spawn Crate Charlie", 	"scripts\spawners\logistics\crates.sqf", "charlie"];
_spawner addaction ["Spawn Crate Delta", 	"scripts\spawners\logistics\crates.sqf", "delta"];
_spawner addaction ["Spawn Crate Echo", 	"scripts\spawners\logistics\crates.sqf", "echo"];
_spawner addaction ["Spawn Crate Foxtrot", 	"scripts\spawners\logistics\crates.sqf", "foxtrot"];
_spawner addaction ["Spawn Crate Golf", 	"scripts\spawners\logistics\crates.sqf", "golf"];
_spawner addaction ["Spawn Crate Hotel",	"scripts\spawners\logistics\crates.sqf", "hotel"];
_spawner addaction ["Spawn Crate India",	"scripts\spawners\logistics\crates.sqf", "india"];
_spawner addaction ["Spawn Crate Juliet", 	"scripts\spawners\logistics\crates.sqf", "juliet"];
_spawner addaction ["Spawn Crate Kilo", 	"scripts\spawners\logistics\crates.sqf", "kilo"];
_spawner addaction ["Spawn Crate Lima", 	"scripts\spawners\logistics\crates.sqf", "lima"];
_spawner addaction ["Spawn Crate Mike",		"scripts\spawners\logistics\crates.sqf", "mike"];
_spawner addaction ["Spawn Crate November", "scripts\spawners\logistics\crates.sqf", "november"];